---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fire9.
--- DateTime: 05/10/2021 15:33
---

function KeyboardInput(TextEntry, ExampleText, MaxStringLenght)

    AddTextEntry('FMMC_KEY_TIP1', TextEntry)
    DisplayOnscreenKeyboard(1, "FMMC_KEY_TIP1", "", ExampleText, "", "", "", MaxStringLenght)
    blockinput = true

    while UpdateOnscreenKeyboard() ~= 1 and UpdateOnscreenKeyboard() ~= 2 do
        Citizen.Wait(0)
    end

    if UpdateOnscreenKeyboard() ~= 2 then
        local result = GetOnscreenKeyboardResult()
        Citizen.Wait(500)
        blockinput = false
        return result
    else
        Citizen.Wait(500)
        blockinput = false
        return nil
    end
end

local MainMenu = RageUI.CreateMenu("Cartel", "Gestion des gangs");
local gangListSubMenu = RageUI.CreateSubMenu(MainMenu, "Cartel", "Liste des gangs")
local gangSubMenu = RageUI.CreateSubMenu(gangListSubMenu, "Cartel", "Gestion - ")

local generate = false
local gangsName = {}
local editGangId
local rightName = ''

function RageUI.PoolMenus:Example()
    MainMenu:IsVisible(function(Items)
        Items:AddButton("Nouveau gang", "Créer un nouveau gang", { IsDisabled = false }, function(onSelected)
            if onSelected then
                --RageUI.CloseAll()
                local name = KeyboardInput('Nom du gang', '', 32)

                if name and name ~= '' then
                    TriggerServerEvent('createGang', name)
                end
            end
        end)

        Items:AddButton("Liste des gangs", "Listing des gangs", {IsDisabled = false}, function(onSelected)
            generate = true
        end, gangListSubMenu)
    end, function()end)

    gangListSubMenu:IsVisible(function(Items)
        if generate then
            TriggerServerEvent("listGang")
            RegisterNetEvent("createListingMenu")
            AddEventHandler("createListingMenu", function(gangs)
                gangsName = gangs
            end)

            generate = false
        end

        for index,data in pairs(gangsName) do
            Items:AddButton(data.name, "Gestion "..data.name, { IsDisabled = false }, function(onSelected)
                if onSelected then
                    gangSubMenu:SetSubtitle("Gestion - "..data.name)
                    editGangId = data.id
                    rightName = ''
                    generate = true
                end
            end, gangSubMenu)
        end

    end, function()end)

    gangSubMenu:IsVisible(function(Item)
        if generate then
            TriggerServerEvent('getChief', editGangId)
            RegisterNetEvent('chiefName')
            AddEventHandler('chiefName', function(nameChief)
                if nameChief ~= nil then
                    rightName = nameChief
                end
            end)
            generate = false
        end

        Item:AddButton("Chef", "Nommer un chef", {IsDisabled = false, RightLabel = rightName}, function(onSelected)
            if onSelected then
                local chiefName = KeyboardInput("Nom du chef (Prenom Nom)", "", 34)

                if chiefName and chiefName ~= '' then
                    TriggerServerEvent('setChief', chiefName, editGangId)
                end
            end
        end)

        Item:AddButton('Business', 'Sélectionner le business', {IsDisabled = false}, function(onSelected)

        end)

        Item:AddButton('PNJ', 'Spawn du PNJ de gang', {IsDisabled = false}, function(onSelected)
            if onSelected then
                local ped = PlayerPedId()
                local pos = GetEntityCoords(ped)
                local heading = GetEntityHeading(ped)

                local pedName = KeyboardInput("Nom du PED", "", 32)

                if pedName and pedName ~= '' then
                    Citizen.CreateThread(function()
                        local hash = GetHashKey( pedName )
                        while not HasModelLoaded( hash ) do
                            RequestModel( hash )
                            Wait(20)
                        end

                        local pnj = CreatePed(9, hash, pos.x, pos.y, pos.z, heading, false, false)
                        SetEntityInvincible(pnj, true)
                        Wait(1000)
                        FreezeEntityPosition(pnj, true)
                    end)

                    TriggerServerEvent('setPnj', editGangId, pos, heading, pedName)
                end
            end

        end)

        Item:AddButton('Dissoudre', 'Dissoudre le gang', {IsDisabled = false}, function(onSelected)

        end)

    end, function()end)
end

Keys.Register("F9", "F9", "Test", function()
    RageUI.Visible(MainMenu, not RageUI.Visible(MainMenu))
end)