---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fire9.
--- DateTime: 05/10/2021 21:52
---

ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

RegisterNetEvent('createGang')
RegisterNetEvent('listGang')
RegisterNetEvent('setChief')
RegisterNetEvent('getChief')
RegisterNetEvent('deleteGang')
RegisterNetEvent('setPnj')
RegisterNetEvent('getPnj')

AddEventHandler('createGang', function(name)
    MySQL.Async.execute("INSERT INTO wf_gangs (nom) VALUE (@name)", {['name'] = name}, function()
        print('Creation du gang '..name..' reussi')
    end)
end)

AddEventHandler('listGang', function()
    local playerId = source
    local gangs = {}

    MySQL.Async.fetchAll("SELECT id, nom FROM wf_gangs", {}, function(result)
        for index,data in pairs(result) do
            table.insert(gangs, {id = data.id, name = data.nom})
        end

        TriggerClientEvent("createListingMenu", playerId, gangs)
    end)
end)

AddEventHandler('setChief', function(chiefName, gangId)
    local names = Split(chiefName, ' ')
    MySQL.Async.fetchAll("SELECT identifier FROM users WHERE firstname = @firstname AND lastname = @lastname", {
        ['firstname'] = names[1],
        ['lastname'] = names[2]
    }, function(result)
        if result[1] then
            MySQL.Async.execute("UPDATE wf_gangs SET id_chef = @identifier WHERE id = @id", {['identifier'] = result[1].identifier, ['id'] = gangId}, function()
                print('Le joueur '..names[1]..' '..names[2]..' est nommer chef du gang '..gangId)
                MySQL.Async.execute("UPDATE users SET id_gang = @idGang WHERE identifier = @identifier", {['idGang'] = gangId, ['identifier'] = result[1].identifier}, function()
                    print('Le joueur '..names[1]..' '..names[2]..' appartien au gang '..gangId)
                end)
            end)
        end
    end)
end)

AddEventHandler('getChief', function(gangId)
    local playerId = source
    MySQL.Async.fetchAll("SELECT users.firstname, users.lastname FROM wf_gangs INNER JOIN users ON wf_gangs.id_chef = users.identifier WHERE wf_gangs.id = @id", {
        ['id'] = gangId
    }, function(result)
        local name
        if result[1] then
            name = result[1].firstname..' '..result[1].lastname
        else
            name = nil
        end

        TriggerClientEvent('chiefName', playerId, name)
    end)
end)

AddEventHandler('deleteGang', function(gangId)
    MySQL.Async.execute("UPDATE users SET id_gang = NULL WHERE id_gang = @idGang", {['idGang'] = gangId}, function()
        MySQL.Async.execute("DELETE FROM wf_gangs WHERE id = @idGang", {['idGang'] = gangId}, function()

        end)
    end)
end)

AddEventHandler('setPnj', function(idGang, position, head, model)
    MySQL.Async.execute("UPDATE wf_gangs SET pos_x = @posX, pos_y = @posY, pos_z = @posZ, heading = @head, model = @model WHERE id = @idGang", {
        ['posX'] = position.x,
        ['posY'] = position.y,
        ['posZ'] = position.z,
        ['head'] = head,
        ['model'] = model,
        ['idGang'] = idGang
    }, function()  end)
end)

AddEventHandler('getPnj', function()
    local src = source
    MySQL.Async.fetchAll("SELECT pos_x, pos_y, pos_z, heading, model FROM wf_gangs WHERE pos_x IS NOT NULL AND pos_y IS NOT NULL AND pos_z IS NOT NULL AND heading IS NOT NULL AND model IS NOT NULL", {},
    function(result)
        TriggerClientEvent('regenPnj', src, result)
    end)
end)

function Split(s, delimiter)
    result = {};
    for match in (s..delimiter):gmatch("(.-)"..delimiter) do
        table.insert(result, match);
    end
    return result;
end